clean bootstrap sequence.

diff --git a/build-aux/icies/auto-all b/build-aux/icies/auto-all
--- a/build-aux/icies/auto-all
+++ b/build-aux/icies/auto-all
@@ -1,20 +1,31 @@
 #!/bin/sh
 # Maintainer: SAITO Fuyuki
-# Time-stamp: <2020/09/15 13:10:57 fuyuki auto-all>
+# Time-stamp: <2021/04/17 16:35:19 fuyuki auto-all>
 # Package: IcIES-2
-# Copyright: 2020 JAMSTEC
+# Copyright: 2020-2021 JAMSTEC
 # Licensed under the Apache License, Version 2.0
 #   (https://www.apache.org/licenses/LICENSE-2.0)
 
-bindir=$(dirname "$0")
-top_srcdir=${bindir}/../..
+bindir=`dirname "$0"`
+
+# health check
+e=0
+for c in find autoreconf python dirname
+do
+  if command -v "$c" > /dev/null 2>&1; then :; else
+    echo "$0: missing command: $c" >&2
+    e=1
+  fi
+done
+test "$e" -gt 0 && echo "$0: aborts" >&2 && exit "$e"
 
 while test $# -gt 0
 do
   case $1 in
   -f) force=-f;;
   -v) verbose=--verbose;;
-  -*) echo "Invalid argument $1." >&2; exit 1;;
+  -*) echo "$0: invalid argument $1." >&2; exit 1;;
+  *)  break;;
   esac
   shift
 done
@@ -24,26 +35,39 @@ done
 mkmkam=$bindir/mkmkam
 tmpl=Makefile.tmpl
 am=Makefile.am
-dir=.
 
-find $dir -name $tmpl |\
+top_srcdir=
+if command -v "git" > /dev/null 2>&1; then
+  chk=`git rev-parse --is-inside-work-tree 2> /dev/null || echo false`
+  if test x"$chk" = xtrue; then
+    top_srcdir=`git rev-parse --show-toplevel` || exit $?
+  fi
+fi
+test x"$top_srcdir" = x && top_srcdir=${bindir}/../..
+
+cd "$top_srcdir" || { echo "$0: cannot cd $top_srcdir" >&2; exit 1; }
+echo "$0: entering $top_srcdir."
+
+find . -name $tmpl |\
   while read -r fs
   do
-    ft=$(dirname "$fs")/$am
+    ft=`dirname "$fs"`/$am
     if test x"$force" = x  -a  -e "$ft"  -a  "$ft" -nt "$fs"; then
-      echo "skip to generate $ft." >&2
+      echo "$0: skip to generate $ft." >&2
     else
-      echo "generate $ft from $fs." >&2
-      $mkmkam "$fs"
+      echo "$0: generate $ft from $fs." >&2
+      $mkmkam "$fs" || exit $?
     fi
   done
 
-{ cd $top_srcdir; m4dir=$(pwd)/build-aux/m4; }
-
+m4dir=build-aux/m4
 if test -d "$m4dir"; then
-  autoreconf $verbose -i -I "${m4dir}"
+  echo "$0: run autoreconf..." >&2
+  autoreconf $verbose -i -I "${m4dir}" || exit $?
 else
   echo "$0: autotools disabled (not found $m4dir)" >&2
   echo "$0: You may run \`autoreconf -i' manually (which may fail)." >&2
   exit 1
 fi
+echo "$0: done" >&2
+exit 0
diff --git a/build-aux/icies/bootstrap b/build-aux/icies/bootstrap
--- a/build-aux/icies/bootstrap
+++ b/build-aux/icies/bootstrap
@@ -1,53 +1,64 @@
 #!/bin/sh
-# Time-stamp: <2020/09/17 18:29:18 fuyuki bootstrap>
-# Copyright: 2011--2020 JAMSTEC
+# Time-stamp: <2021/04/19 08:33:20 fuyuki bootstrap>
+# Copyright: 2011-2021 JAMSTEC
 # Licensed under the Apache License, Version 2.0
 #   (https://www.apache.org/licenses/LICENSE-2.0)
 
-d=`dirname $0`
+d=`dirname "$0"`
 
 MAGIC='It was a dark and stormy night'
+
+DEFS="auto-all tree-all"
+OPTS="hooks-all"
+
+CMDS="$DEFS"
+test x"$1" = x-m && shift && CMDS="$CMDS $OPTS"
 
 if test "$1" = "$MAGIC"; then
   :
 else
-  cat <<EOF >&2
------------------------------------
- bootstrap for IcIES-2 preparation
------------------------------------
-This script calls sequentially two scripts to construct some
-(hopefully) useful files on clean resources obtained from, e.g., git
-repository.  Mostly you do not have to run this script, in particular,
-when you obtain the resources as a tar archive file.
+  cat << EOF >&2
+-----------------------
+ bootstrap for IcIES-2
+-----------------------
+This script calls some scripts to construct files on clean resources
+obtained from, e.g., git repository.  Mostly you do not have to run
+this script, in particular, when you obtain the resources as a tar
+archive file.
 
-  $d/tree-all - generate TreeID file which records current git hash id
-  $d/auto-all - generate Makefile.am's from Makefile.tmpl's, and run 'autoreconf'
+  $d/auto-all - generate 'Makefile.am's from 'Makefile.tmpl's, and run 'autoreconf'
+  $d/tree-all - generate TreeID to record revision properties
+  $d/hooks-all - install files in $d/hooks as githooks
 
 In case you doubt, please confirm the scripts.
 
-If you are sure, 'rerun' this script with a magic argument:
+If you are sure, *rerun* this script with a magic argument:
 
-   $0 '$MAGIC'
+   $0 '$MAGIC'        # run {$DEFS}
+   $0 -m '$MAGIC'     # also run {$OPTS}
 
 Note that you may need to quote the argument to be interpreted as single.
 
-Optionally, you may run the following script directly to enable automatic updates
-of TreeID file using git hook system:
-
-  $d/hooks-all - install files in $d/icies/hooks
-
 ----------------------------------------
-$0: Aborted
+$0: aborted
 ----------------------------------------
 EOF
   exit 1
 fi
 
 echo "$0: start..."
-for c in tree-all auto-all
+for c in $CMDS
 do
   c=$d/$c
-  test -x $c && $c $@
+  if test -x "$c"; then
+    echo "$0: run '$c'" >&2
+    $c; e=$?
+     if test $e -ne 0 ; then
+       echo "$0: failed while '$c'" >&2
+       echo "$0: err=$e" >&2
+       exit $e
+     fi
+  fi
 done
 echo "$0: done"
 exit 0
diff --git a/build-aux/icies/tree-all b/build-aux/icies/tree-all
--- a/build-aux/icies/tree-all
+++ b/build-aux/icies/tree-all
@@ -1,13 +1,24 @@
 #!/bin/sh
-# Time-stamp: <2020/09/15 12:24:00 fuyuki tree-all>
-# Copyright: 2011--2020 JAMSTEC
+# Maintainer: SAITO Fuyuki
+# Time-stamp: <2021/04/19 08:12:38 fuyuki tree-all>
+# Copyright: 2011-2021 JAMSTEC
 # Licensed under the Apache License, Version 2.0
 #   (https://www.apache.org/licenses/LICENSE-2.0)
 
-d=`dirname $0`/tree
+bindir=`dirname "$0"`
 
-for c in pkggen idgen listgen
-do
-  c=$d/$c
-  test -x $c && $c $@
-done
+top_srcdir=
+if command -v "git" > /dev/null 2>&1; then
+  chk=`git rev-parse --is-inside-work-tree 2> /dev/null || echo false`
+  if test x"$chk" = xtrue; then
+    top_srcdir=`git rev-parse --show-toplevel` || exit $?
+  fi
+fi
+test x"$top_srcdir" = x && top_srcdir=${bindir}/../..
+
+idgen=$bindir/idgen
+
+test -x $idgen || { echo "Cannot run $idgen." >&2; exit 1; }
+
+$idgen $top_srcdir/TreeID || exit $?
+exit 0
